// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	maps\_custom_utility::detach_all_attachments();
	self setModel("body_shadow_co_smg");
	self attach("head_shadow_co_c", "", true);
	self.voice = "british";
	maps\_custom_utility::detach_all_attachments();
}

precache()
{
	precacheModel("body_shadow_co_smg");
	precacheModel("head_shadow_co_c");
}
