// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	maps\_custom_utility::detach_all_attachments();
	self setModel("body_airport_com_a");
	self attach("h2_head_vil_makarov", "", true);
	self.voice = "british";
	maps\_custom_utility::detach_all_attachments();
}

precache()
{
	precacheModel("body_airport_com_a");
	precacheModel("h2_head_vil_makarov");
}
